Repository retaildevcrews/istio, pull requests merged in 2021-09, with the labels that each got.

#41 updated image
  .devcontainer/Dockerfile
Labels: TechnicalDebt

#43 Feature/burst isolation
  Makefile
  burst/Makefile
  burst/Ngsa.BurstService.csproj
  burst/README.md
  burst/deploy/burst-dev.yaml
  burst/deploy/gw-burst.yaml
  clusteradm/Makefile
  clusteradm/patch.sh
  deploy/kind/kind.yaml
  deploy/loderunner/baseline.json
  deploy/loderunner/benchmark.json
  deploy/loderunner/memory-baseline.json
  deploy/loderunner/memory-benchmark.json
  deploy/ngsa-memory/filter.yaml
  deploy/ngsa-memory/ngsa-memory.yaml
Labels: DevExperience, PlatValidApp

#44 Ingress Controller Envoy Wasm Filter Spike/POC
  spikes/istio-ingress-filter/Makefile
  spikes/istio-ingress-filter/README.md
  spikes/istio-ingress-filter/istio-ingress/ingress-filter.yaml
  spikes/istio-ingress-filter/istio-ingress/ingress-patch.yaml
Labels: DesignReview, SPIKE
