Repository retaildevcrews/istio, pull requests merged in 2021-08, with the labels that each got.

#17 added diagram
  README.md
  deploy/mem1/filter.yaml
  deploy/mem2/filter.yaml
  deploy/mem3/filter.yaml
  deploy/ngsa-memory/filter.yaml
  images/flow.png
  patch.sh
Labels: Documentation

#18 added user-agent check
  Cargo.toml
  Makefile
  deploy/mem1/filter.yaml
  deploy/mem2/filter.yaml
  deploy/mem3/filter.yaml
  deploy/ngsa-memory/filter.yaml
  src/lib.rs
Labels: CustomerFeedback

#20 standardized logging
  Makefile
  deploy/mem1/filter.yaml
  deploy/mem2/filter.yaml
  deploy/mem3/filter.yaml
  deploy/ngsa-memory/filter.yaml
  src/lib.rs
Labels: TechnicalDebt

#25 updates for demo
  .devcontainer/devcontainer.json
  Makefile
  deploy/kind/kind.yaml
Labels: Bug, InternalFeedback

#24 Pod count as load metrics in BurstMetrics Service
  burst/src/Controllers/BurstMetricsController.cs
  burst/src/K8sApi/K8sHPAMetrics.cs
  burst/src/K8sApi/K8sHPAMetricsService.cs
Labels: BLOCKED, Enhancement

#36 updated DevX
  .devcontainer/devcontainer.json
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  .devcontainer/post-start.sh
  Makefile
  README.md
  burst/.dockerignore
  burst/Makefile
  burst/Ngsa.BurstService.csproj
  burst/README.md
  burst/secrets/CosmosCollection
  burst/secrets/CosmosDatabase
  burst/secrets/CosmosUrl
  burst/src/Core/CommandLine.cs
  burst/src/Core/Config.cs
  burst/src/Program.cs
  burst/swagger.json
  clusteradm/Makefile
  clusteradm/patch.sh
  deploy/dashboards/dotnet.json
  deploy/dashboards/ngsa.json
  deploy/fluentbit/account.yaml
  deploy/fluentbit/fluentbit-pod.yaml
  deploy/fluentbit/log.yaml
  deploy/fluentbit/stdout-config.yaml
  deploy/grafana/datasource.yaml
  deploy/grafana/deployment.yaml
  deploy/grafana/namespace.yaml
  deploy/grafana/service.yaml
  deploy/grafanadata/grafana.db
  deploy/kiali/crd.yaml
  deploy/kiali/service.yaml
  deploy/mem1/app.yaml
  deploy/mem1/filter.yaml
  deploy/mem1/gw.yaml
  deploy/mem2/app.yaml
  deploy/mem2/filter.yaml
  deploy/mem2/gw.yaml
  deploy/mem3/app.yaml
  deploy/mem3/filter.yaml
  deploy/mem3/gw.yaml
  deploy/ngsa-memory/filter.yaml
  deploy/prometheus/1-clusterRole.yaml
  deploy/prometheus/2-config-map.yaml
  deploy/prometheus/3-prometheus-deployment.yaml
  deploy/prometheus/4-prometheus-service.yaml
  patch.sh
Labels: Bug, DevExperience, REFACTOR

#38 Burst Metrics Service documentation
  burst/README.md
Labels: Documentation, PlatValidApp

#39 updated per design review
  .devcontainer/post-start.sh
  burst/Makefile
  burst/deploy/burst.yaml
  burst/deploy/gw-burst.yaml
  clusteradm/Makefile
  deploy/ngsa-memory/filter.yaml
  spikes/cmexamples/README.MD
  spikes/deploy-pymetric/pymetric-gw.yaml
  spikes/deploy-pymetric/pymetric.yaml
  spikes/pymetric/Dockerfile
  spikes/pymetric/server.py
Labels: DesignReview, DevExperience, InternalFeedback
