Repository retaildevcrews/istio, pull requests merged in 2021-07, with the labels that each got.

#9 updated codespaces build
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-install.sh
Labels: Bug

#10 added sample code
  .devcontainer/post-install.sh
  Makefile
  README.md
  deploy/filter.yml
  deploy/kind/config.yaml
  deploy/kind/kind.yaml
  deploy/loderunner/baseline.json
  deploy/loderunner/benchmark.json
  deploy/loderunner/loderunner.yaml
  deploy/ngsa-memory/ngsa-gw.yaml
  deploy/ngsa-memory/ngsa-memory.yaml
  deploy/pymetric/pymetric.yaml
  patch.sh
  pymetric/server.py
  src/lib.rs
Labels: SPIKE

#11 use config instead of hard-coded values
  Makefile
  deploy/filter.yml
  patch.sh
  src/lib.rs
Labels: Bug, TechnicalDebt

#13 Feature/burst service
  Makefile
  burst/Controllers/ApiController.cs
  burst/K8sApi/K8sHPAMetrics.cs
  burst/K8sApi/K8sMetricsService.cs
  burst/Startup.cs
  burst/burst.csproj
  deploy/burst/burst.yaml
Labels: DesignReview, Enhancement

#16 updated demo
  .devcontainer/post-install.sh
  Makefile
  README.md
  deploy/mem1/README.md
  deploy/mem1/filter.yaml
  deploy/mem2/README.md
  deploy/mem2/filter.yaml
  deploy/mem3/README.md
  deploy/mem3/filter.yaml
  deploy/ngsa-memory/README.md
  deploy/ngsa-memory/filter.yaml
  patch.sh
  src/lib.rs
Labels: InternalFeedback
