Repository retaildevcrews/istio, pull requests merged in 2022-02, with the labels that each got.

#49 Added CI for burst-service
  .github/workflows/burst.yaml
Labels: size: S

#52 HPA with custom metrics from Prometheus
  .devcontainer/devcontainer.json
  Makefile
  README.md
  clusteradm/Makefile
  deploy/k3d/k3d.yaml
  deploy/metrics/components.yaml
  deploy/ngsa-memory/ngsa-memory.yaml
  deploy/prometheus/hpa-custom-metrics.yaml
  deploy/prometheus/prom-adapter-helm-values.yaml
  deploy/prometheus/prometheus.yaml
Labels: DevX, size: M, Istio, AppBursting

#53 Update GetK8SHPAMetrics function to use dictionary instead of iterating through List
  burst/Dockerfile
  burst/Ngsa.BurstService.csproj
  burst/README.md
  burst/src/K8sApi/K8sHPAMetricsService.cs
  burst/src/K8sApi/K8sHpaMap.cs
Labels: DesignReview, MetricsService, AppBursting

#54 Build fail: First time build fails on merge
  burst/src/K8sApi/K8sHpaMap.cs
Labels: Bug, CI/CD, AppBursting

#57 Update readme diagram
  README.md
Labels: Sharing
